// Auto-generated by binary_to_compressed_c from NotoSans-Regular.ttf
// Do not edit manually.
#pragma once
extern const unsigned int  NotoSans_Regular_compressed_size;
extern const unsigned char NotoSans_Regular_compressed_data[];
